// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWERD89eRbrnxkqbDee8v20KlK6KrhiuI',
    appId: '1:360679129146:web:34a584ccfcb55d2df77503',
    messagingSenderId: '360679129146',
    projectId: 'bazasplitup',
    authDomain: 'bazasplitup.firebaseapp.com',
    storageBucket: 'bazasplitup.firebasestorage.app',
    measurementId: 'G-QV5ZNMLP7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmNdEYtaeZg7Kk0mZWCXgZfKHcquPYUM0',
    appId: '1:360679129146:android:7f81a72c9b3f795df77503',
    messagingSenderId: '360679129146',
    projectId: 'bazasplitup',
    storageBucket: 'bazasplitup.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBReYsNEheEh-t4-WmAd5OVQLy31O7cO4A',
    appId: '1:360679129146:ios:aa0fdbfb7341b200f77503',
    messagingSenderId: '360679129146',
    projectId: 'bazasplitup',
    storageBucket: 'bazasplitup.firebasestorage.app',
    iosBundleId: 'com.example.splitup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBReYsNEheEh-t4-WmAd5OVQLy31O7cO4A',
    appId: '1:360679129146:ios:aa0fdbfb7341b200f77503',
    messagingSenderId: '360679129146',
    projectId: 'bazasplitup',
    storageBucket: 'bazasplitup.firebasestorage.app',
    iosBundleId: 'com.example.splitup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWERD89eRbrnxkqbDee8v20KlK6KrhiuI',
    appId: '1:360679129146:web:1ddf30fdfdedc64df77503',
    messagingSenderId: '360679129146',
    projectId: 'bazasplitup',
    authDomain: 'bazasplitup.firebaseapp.com',
    storageBucket: 'bazasplitup.firebasestorage.app',
    measurementId: 'G-W2JFZ0MK4V',
  );
}
